config/routes.rb
Rails.application.routes.draw do
  devise_for :nutritionists, :skip => [:registrations] 
  devise_scope :nutritionist do
    authenticated :nutritionist do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  post 'user_token' => 'user_token#create'
  resources :foods, except: [:show]
  resources :diets, only: [:show, :edit, :update]
  resources :meals, only: [:new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# ==================================
  # API subdomain
  # ==================================
  namespace :api, defaults: { format: 'json' } do
    namespace :v1, defaults: { format: 'json' } do
      resources :foods, :categories, :physical_activities, :goals, only: [:index]
      resources :diets, only: [:index, :show]
      post '/diets/request_for_diet', to: 'diets#create', as: 'request_for_diet'
      resources :facebook_user_token, :customers, only: [:create]
      
      #custom user routes
      get '/users/current', to: 'users#current', as: 'current_user'

      #payment
      post '/payments/create', to: 'payments#pay_diet', as: 'pay_diet'
      get '/payments/get-key', to: 'payments#stripe_key', as: 'get_stripe_key'
    end
    match '(*path)', to: 'errors#routing', via: :all
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :food_category
  has_and_belongs_to_many :customers
  
  validates :name, presence: { :message => :inclusion }
end

app/controllers/api/v1/foods_controller.rb
module API
    module V1
        class FoodsController < APIController
            before_action :authenticate_user, :check_permissions
            
            def index
                if (params.has_key?(:category_id)) 
                    @foods = Food.where(food_category_id: params[:category_id])
                else
                    @foods = Food.all
                end 
                render json: @foods, each_serializer: FoodSerializer
            end
        end
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :create]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, :flash => { :success => "Se ha creado la comida" } }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to foods_path, :flash => { :success => "Se ha actualizado la comida" } }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_path, :flash => { :success => "Se ha eliminado la comida" } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    def set_categories
      @categories = FoodCategory.all
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :food_category_id)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :food_category_id %>
    <%= form.text_field :food_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container">
<h1>Editar comida</h1>
<%= link_to 'Regresar', foods_path, class: 'btn btn-light btn-small' %>
<br>
<br>
<% if @food.errors.any? %>
    <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h4><%= pluralize(@food.errors.count, "error")%></h4>
      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>
<%= form_for @food do |f| %>
<div class="form-group">
  <%= f.label 'Nombre' %><br />
  <%= f.text_field :name, autofocus: true, autocomplete: "content", placeholder: "Escribe el nombre de la comida", :class => 'form-control form-control-lg' %>
</div>
  <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/foods/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Comidas</h1>
<br>
<%= link_to 'Regresar', "/", class: 'btn btn-light btn-small' %>
<br>
<br>
<%= link_to 'Registrar comida', new_food_path, class: 'btn btn-success btn-small white-words' %>
<br>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Categoría</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.food_category.name %></td>
        <td><%= link_to 'Editar', edit_food_path(food) %></td>
        <td><%= link_to 'Eliminar', food, method: :delete, data: { confirm: 'Estás seguro de eliminar esta comida?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/foods/new.html.erb
<div class="container">
<h1>Nueva comida</h1>
<p>Estas son las comidas que los clientes ven y seleccionan</p>
<%= link_to 'Regresar', foods_path, class: 'btn btn-light btn-small' %>
<br>
<br>
<% if @food.errors.any? %>
    <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h4><%= pluralize(@food.errors.count, "error")%></h4>
      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    </div>
  <% end %>
<%= form_for @food do |f| %>
<div class="form-group">
  <%= f.label 'Categoría' %><br />
  <%= f.select :food_category_id, options_from_collection_for_select(@categories, 'id', 'name'), {}, { :class => 'form-control form-control-lg' } %>
</div>
<div class="form-group">
  <%= f.label 'Nombre' %><br />
  <%= f.text_field :name, autofocus: true, autocomplete: "content", placeholder: "Escribe el nombre de la comida", :class => 'form-control form-control-lg' %>
</div>
  <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Food category:</strong>
  <%= @food.food_category_id %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>