config/routes.rb
Rails.application.routes.draw do
  devise_for :nutritionists, :skip => [:registrations] 
  devise_scope :nutritionist do
    authenticated :nutritionist do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  post 'user_token' => 'user_token#create'
  resources :foods, except: [:show]
  resources :diets, only: [:show, :edit, :update]
  resources :meals, only: [:new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# ==================================
  # API subdomain
  # ==================================
  namespace :api, defaults: { format: 'json' } do
    namespace :v1, defaults: { format: 'json' } do
      resources :foods, :categories, :physical_activities, :goals, only: [:index]
      resources :diets, only: [:index, :show]
      post '/diets/request_for_diet', to: 'diets#create', as: 'request_for_diet'
      resources :facebook_user_token, :customers, only: [:create]
      
      #custom user routes
      get '/users/current', to: 'users#current', as: 'current_user'

      #payment
      post '/payments/create', to: 'payments#pay_diet', as: 'pay_diet'
      get '/payments/get-key', to: 'payments#stripe_key', as: 'get_stripe_key'
    end
    match '(*path)', to: 'errors#routing', via: :all
  end
end

app/models/diet.rb
class Diet < ApplicationRecord
    enum status: [ :requested, :approved, :paid, :expired ]

    belongs_to :customer
    has_many :meals
end

app/controllers/api/v1/diets_controller.rb
module API
    module V1
        class DietsController < APIController
            include Constants
            before_action :authenticate_user, :check_permissions

            def index
                diets = Diet.all.order(created_at: :desc)
                render json: diets, each_serializer: DietSerializer
            end

            def show
                diet = Diet.find(params[:id])
                render json: diet, serializer: DietDetailSerializer
            end

            def create
                #first step
                #customer requests a diet
                if current_user.customer.can_request_diet
                    diet = Diet.new
                    diet.price = DEFAULT_DIET_PRICE
                    diet.customer = current_user.customer
                    if diet.save
                        update_customer
                        render json: diet, serializer: DietSerializer
                    else
                        raise Error::UnprocessableEntity
                    end
                else
                    raise Error::CannotRequestDiet
                end
            end

            private

            def update_customer
                current_user.customer.can_request_diet = false
                current_user.customer.save
            end
        end
    end
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  helper TimeZoneConverter
  before_action :set_diet, only: [:show, :edit, :update, :destroy]

  # GET /diets
  # GET /diets.json
  def index
    @diets = Diet.order('updated_at')
  end

  # GET /diets/1
  # GET /diets/1.json
  def show
    @diet = DietViewObject.new(@diet)
  end

  # GET /diets/new
  def new
    @diet = Diet.new
  end

  # GET /diets/1/edit
  def edit
    validate_diet_edition
    @diet = DietViewObject.new(@diet)
  end

  # POST /diets
  # POST /diets.json
  def create
    @diet = Diet.new(diet_params)

    respond_to do |format|
      if @diet.save
        format.html { redirect_to @diet, notice: 'Diet was successfully created.' }
        format.json { render :show, status: :created, location: @diet }
      else
        format.html { render :new }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diets/1
  # PATCH/PUT /diets/1.json
  def update
    set_diet_status
    respond_to do |format|
      if @diet.update(diet_params)
        format.html { redirect_to @diet, :flash => { :success => "Se ha actualizado la dieta correctamente" } }
        format.json { render :show, status: :ok, location: @diet }
      else
        format.html { render :edit }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diets/1
  # DELETE /diets/1.json
  def destroy
    @diet.destroy
    respond_to do |format|
      format.html { redirect_to diets_url, notice: 'Diet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diet
      @diet = Diet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diet_params
      params.require(:diet).permit(:recommendations)
    end

    def set_diet_status
      if @diet.requested?
        @diet.status = :approved
      end
    end

    def validate_diet_edition
      if @diet.expired?
        redirect_to "/"
      end
    end

end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/diets/_form.html.erb
<%= form_with(model: diet, local: true) do |form| %>
  <% if diet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
        <% diet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diets/edit.html.erb
<div class="container">
<h1>Actualizar dieta</h1>
<%= link_to 'Regresar', @diet.to_model, class: 'btn btn-light btn-small' %>
<br><br>
<% if @diet.canAddMeals %>
  <%= link_to "Agregar comidas", new_meal_url(diet_id: @diet.id), method: :get, :class => 'btn btn-success white-words' %>
<% end %>

<br><br>


<% @diet.mealsPerType.each do |meal_type, meals| %>
  <br>
  <h4><%= I18n.t('meals.type.'+ meal_type) %></h4>
  <br>
  <table class="table table-bordered">
  <thead>
  <tr>
  <th scope="col">Contenido</th>
  <th scope="col">Acción</th>
  </tr>
  </thead>
  <tbody>
  <% meals.each do |meal| %>
    <tr>
    <td><%= meal.content %></td>
    <td>
      <%= link_to 'Editar', edit_meal_path(meal.id), class: "btn btn-light" %> 
      <%= link_to 'Eliminar', meal_path(meal), method: :delete, data: { confirm: '¿Estás seguro de eliminar esta comida?' }, class: "btn btn-danger btn-small white-words" %>
    </td>
    </tr>
    <% end %>
    
    </tbody>
    </table>
    <% end %>

    <% if @diet.canEdit %>
      <%= form_for(@diet.to_model, :url => diet_path, :method => :put) do |f| %>
        <div class="form-group">
        <%= f.label :recomendaciones %><br />
        <%= f.text_area :recommendations, autofocus: true, autocomplete: "content", :class => 'form-control form-control-lg ' %>
        </div>
          <%= f.submit "Guardar", :class => 'btn btn-info' %>
          <% end %>
          </div>
          <br>
    <% end %>

app/views/diets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= link_to 'Show', diet %></td>
        <td><%= link_to 'Edit', edit_diet_path(diet) %></td>
        <td><%= link_to 'Destroy', diet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diet', new_diet_path %>

app/views/diets/new.html.erb
<h1>New Diet</h1>

<%= render 'form', diet: @diet %>

app/views/diets/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h2>Detalle de dieta</h2>
<%= link_to 'Regresar', "/", class: 'btn btn-light btn-small' %>
<br><br>
<div class='row justify-content-center'>
    <div class="col-8 col-sm-11">
      <b>Estado: </b>  
      <% if @diet.status.eql? "requested" %>
        <button type="button" class="btn btn-warning btn-sm">Solicitado</button>
        <% elsif @diet.status.eql? 'approved' %>
        <button type="button" class="btn btn-info btn-sm">Aprobado</button>
        <% elsif @diet.status.eql? 'paid' %>
        <button type="button" class="btn btn-success btn-sm">Pagado</button>
        <% elsif @diet.status.eql? 'expired' %>
        <button type="button" class="btn btn-danger btn-sm">Expirado</button>
        <% end %>
    </div>
    <div class="col-4 col-sm-1">
    <% if !@diet.status.eql? 'expired' %>
      <%= link_to 'Editar', edit_diet_path(@diet.id), class: "btn btn-light btn-small" %> 
    <% end %>
    </div>
  </div>
  <br><br>
<h4>Datos del usuario</h4>
<br>
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Dato</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><b>Nombre</b></td>
        <td><%= @diet.customer.user.first_name %> <%= @diet.customer.user.last_name %></td>
      </tr>
      <tr>
      <td><b>Edad</b></td>
      <td><%= @diet.customer.age %> años</td>
      </tr>
      <tr>
      <td><b>Ocupación</b></td>
      <td><%= @diet.customer.occupation %></td>
      </tr>
      <tr>
      <td><b>Peso</b></td>
      <td><%= @diet.customer.weight %> kg</td>
      </tr>
      <tr>
      <td><b>Altura</b></td>
      <td><%= @diet.customer.height %> mts</td>
      </tr>
      <tr>
      <td><b>IMC</b></td>
      <td><%= @diet.customer.imc %></td>
      </tr>
      <tr>
      <td><b>No. de comidas al día</b></td>
      <td><%= @diet.customer.daily_foods %></td>
      </tr>
      <tr>
      <td><b>Padecimiento</b></td>
      <td><%= @diet.customer.disease %></td>
      </tr>
      <tr>
      <td><b>Objetivo</b></td>
      <td><%= @diet.customer.goals.first.name %></td>
      </tr>
      <tr>
      <td><b>Ejercicio</b></td>
      <td><%= @diet.customer.physical_activities.first.name %></td>
      </tr>
      <tr>
      <td><b>Comidas</b></td>
      <td>
        <% @diet.customer.foods.each do |food| %>
            <p><%= food.name %></p>
        <% end %>
      </td>
      </tr>
    </tbody>
  </table>

    <h3>Datos de la dieta</h3>
    <br>
    <p><b>Fecha de solicitud: </b><%= l with_mx_time_zone(@diet.created_at), format: :date_with_time %></p>
    <p><b>Fecha de expiración: </b><%= l with_mx_time_zone(@diet.expiration_date), format: :date_with_time unless @diet.expiration_date == nil %></p>
    
    <br>
    <h4>Menú registrado</h4>
      <% @diet.mealsPerType.each do |meal_type, meals| %>
        <br>
          <h5><%= I18n.t('meals.type.'+ meal_type) %></h5>
          <ul>
          <% meals.each do |meal| %>
            <li><%= meal.content %></li>
          <% end %>
          </ul>
        <% end %>

</div>