config/routes.rb
Rails.application.routes.draw do
  devise_for :nutritionists, :skip => [:registrations] 
  devise_scope :nutritionist do
    authenticated :nutritionist do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  post 'user_token' => 'user_token#create'
  resources :foods, except: [:show]
  resources :diets, only: [:show, :edit, :update]
  resources :meals, only: [:new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# ==================================
  # API subdomain
  # ==================================
  namespace :api, defaults: { format: 'json' } do
    namespace :v1, defaults: { format: 'json' } do
      resources :foods, :categories, :physical_activities, :goals, only: [:index]
      resources :diets, only: [:index, :show]
      post '/diets/request_for_diet', to: 'diets#create', as: 'request_for_diet'
      resources :facebook_user_token, :customers, only: [:create]
      
      #custom user routes
      get '/users/current', to: 'users#current', as: 'current_user'

      #payment
      post '/payments/create', to: 'payments#pay_diet', as: 'pay_diet'
      get '/payments/get-key', to: 'payments#stripe_key', as: 'get_stripe_key'
    end
    match '(*path)', to: 'errors#routing', via: :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :foods
    has_and_belongs_to_many :goals
    has_and_belongs_to_many :physical_activities
    has_many :diets
end

app/models/diet.rb
class Diet < ApplicationRecord
    enum status: [ :requested, :approved, :paid, :expired ]

    belongs_to :customer
    has_many :meals
end

app/models/diet_meal.rb
class Meal < ApplicationRecord
    enum weekday: [ :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday ]
    belongs_to :diet
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :food_category
  has_and_belongs_to_many :customers
  
  validates :name, presence: { :message => :inclusion }
end

app/models/food_category.rb
class FoodCategory < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_and_belongs_to_many :customers
end

app/models/meal.rb
class Meal < ApplicationRecord
    enum meal_type: [:breakfast, :morning_snack, :lunch, :evening_snack, :dinner]

    belongs_to :diet

    validates :content, presence: { :message => :inclusion }
end

app/models/nutritionist.rb
class Nutritionist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/physical_activity.rb
class PhysicalActivity < ApplicationRecord
    has_and_belongs_to_many :customer
end

app/models/user.rb
class User < ApplicationRecord
    enum role: [ :customer, :admin ]
    has_one :customer
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper TimeZoneConverter
  
  def index
    if (!params.has_key?(:status) or params[:status].eql?"all")
      @diets = Diet.order(created_at: :desc).page params[:page]
    else
      @diets = Diet.where(status: params[:status]).order(created_at: :desc).page params[:page]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
    def convertMXNPesosToCents(amount)
        amount * 100
    end
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/time_zone_converter.rb
module TimeZoneConverter
    def with_mx_time_zone(time)
      return nil unless time.instance_of? ActiveSupport::TimeWithZone
      time.in_time_zone('Mexico City')
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NutritionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav justify-content-end">
      <%- if nutritionist_signed_in? %>
        <div class="container-fluid px-0">
    <nav class="navbar navbar-expand-md navbar-light bg-white p-0"> <a class="navbar-brand mr-4" href="/"><strong>NutryApp</strong></a> <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item"> 
                  <%= link_to 'Comidas', foods_path, :class=>"nav-link" %>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_nutritionist.name %>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'Cerrar sesión', destroy_nutritionist_session_path, method: :delete, :class => 'dropdown-item' %><% end %>
                  </div> 
                </li>
            </ul>
        </div>       
    </ul>
      <div class= "container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
         </div>
      <% end %>
      </div>
    <%= yield %>
  </body>
</html>